### ISSUE TITLE
Client(String, int) throws UnknownFormatConversionException

### ISSUE THREAD

**Issue by Elewyth** [thejamesthomas/javabank#12]
Using the Client(String, int) constructor throws an UnknownFormatConversionException, because %i is not supported (should be %d).

Reproduce:
`Client client = new Client("localhost", 2525);` (Yes, this is the default, but just to demonstrate)

**Comment by tstphnsn** [comment]
FYI: This should be resolved now.

**Comment by thejamesthomas** [comment]
Sweet! I'll close this issue once I get a new version deployed with Travis.

**Comment by VinayBerry** [comment]
Will this be getting deployed?  The latest published version still doesnt have this update.
